'use strict';

const crypto=require('crypto');
const parser=require('./parser-spine.js');
const semantic=require('./semantic-graph.js');

const AUTHORITY=Object.freeze({workspaceRead:false,workspaceMutation:false,toolExecution:false,network:false,install:false,promotion:false,canon:false});
function hash(v){return crypto.createHash('sha256').update(parser.canon(v)).digest('hex');}
function build({graphs=[],crossEdges=[]}={}){if(!Array.isArray(graphs)||!Array.isArray(crossEdges))throw Error('PROJECT_GRAPH_INPUT_INVALID');const docs=[],nodes=[],edges=[];const graphIds=new Set();for(const g of graphs){if(!g||g.schema!=='axm.code.semantic-graph.v1'||g.result!=='SEMANTIC_GRAPH_READY')throw Error('PROJECT_GRAPH_SEMANTIC_GRAPH_INVALID');if(graphIds.has(g.graphSha256))throw Error('PROJECT_GRAPH_DUPLICATE_GRAPH');graphIds.add(g.graphSha256);docs.push({documentId:g.documentId,languageId:g.languageId,sourceSha256:g.sourceSha256,graphSha256:g.graphSha256});nodes.push(...g.nodes.map(n=>({...n,sourceGraphSha256:g.graphSha256})));edges.push(...g.edges.map(e=>({...e,sourceGraphSha256:g.graphSha256})));}const ids=new Set(nodes.map(n=>n.nodeId));if(ids.size!==nodes.length)throw Error('PROJECT_GRAPH_NODE_ID_COLLISION');for(let i=0;i<crossEdges.length;i++){const x=crossEdges[i];if(!x||typeof x!=='object'||!semantic.EDGE_KINDS.includes(String(x.kind||'')))throw Error(`PROJECT_CROSS_EDGE_INVALID:${i}`);const from=String(x.from||''),to=String(x.to||'');if(!ids.has(from)||!ids.has(to))throw Error(`PROJECT_CROSS_EDGE_NODE_UNKNOWN:${i}`);const base={kind:String(x.kind),from,to,nativeKind:x.nativeKind==null?null:String(x.nativeKind),attributes:x.attributes&&typeof x.attributes==='object'&&!Array.isArray(x.attributes)?JSON.parse(JSON.stringify(x.attributes)):null,sourceGraphSha256:null};const edgeId=String(x.edgeId||`pxe.${hash({...base,i}).slice(0,28)}`);edges.push({edgeId,...base,edgeSha256:hash({edgeId,...base})});}if(new Set(edges.map(e=>e.edgeId)).size!==edges.length)throw Error('PROJECT_GRAPH_EDGE_ID_COLLISION');const core={schema:'axm.code.project-semantic-graph.v1',version:'1.0.0',result:'PROJECT_GRAPH_READY',documentCount:docs.length,nodeCount:nodes.length,edgeCount:edges.length,documents:docs,nodes,edges,truth:{nativeFactsRetained:true,crossEdgesRequireExplicitEvidence:true,graphIsNotRuntimeProof:true,aiRequired:false,networkRequired:false},authority:AUTHORITY};return Object.freeze({...core,projectGraphSha256:hash(core)});}
function impact({graph,nodeId,directions=['out'],edgeKinds=null,maxDepth=8,maxNodes=10000}={}){if(!graph||graph.schema!=='axm.code.project-semantic-graph.v1')throw Error('PROJECT_GRAPH_REQUIRED');const start=String(nodeId||'');if(!graph.nodes.some(n=>n.nodeId===start))return Object.freeze({schema:'axm.code.project-impact-report.v1',result:'UNKNOWN_NODE',nodeId:start,authority:'NONE'});const kinds=edgeKinds==null?null:new Set(edgeKinds.map(String));const dirs=new Set(directions.map(String));const adjacency=new Map();function add(a,e,next,dir){if(!adjacency.has(a))adjacency.set(a,[]);adjacency.get(a).push({edge:e,next,direction:dir});}for(const e of graph.edges){if(kinds&&!kinds.has(e.kind))continue;if(dirs.has('out'))add(e.from,e,e.to,'out');if(dirs.has('in'))add(e.to,e,e.from,'in');}const seen=new Map([[start,0]]),queue=[start],walk=[];while(queue.length){const cur=queue.shift(),depth=seen.get(cur);if(depth>=maxDepth)continue;const nexts=(adjacency.get(cur)||[]).sort((a,b)=>a.edge.edgeId.localeCompare(b.edge.edgeId));for(const x of nexts){walk.push({fromNodeId:cur,edgeId:x.edge.edgeId,edgeKind:x.edge.kind,toNodeId:x.next,direction:x.direction,depth:depth+1});if(!seen.has(x.next)){if(seen.size>=maxNodes)break;seen.set(x.next,depth+1);queue.push(x.next);}}if(seen.size>=maxNodes)break;}const nodeIds=[...seen.keys()];const core={schema:'axm.code.project-impact-report.v1',version:'1.0.0',result:seen.size>=maxNodes?'IMPACT_TRUNCATED':'IMPACT_READY',projectGraphSha256:graph.projectGraphSha256,startNodeId:start,maxDepth,maxNodes,reachedNodeCount:nodeIds.length,nodeIds,walk,truth:{graphReachabilityIsImpactCandidateNotBehaviorProof:true,aiRequired:false,networkRequired:false},authority:AUTHORITY};return Object.freeze({...core,impactSha256:hash(core)});}
module.exports={AUTHORITY,build,impact};
