'use strict';

const crypto=require('crypto');
const parser=require('./parser-spine.js');
const AUTHORITY=Object.freeze({workspaceRead:false,workspaceMutation:false,toolExecution:false,network:false,install:false,promotion:false,canon:false});
const EDGE_KINDS=Object.freeze(['DEFINITION','REFERENCE','IMPORT','DEPENDENCY','CALL','IMPLEMENTATION','TYPE_RELATION','SCHEMA_CONTRACT','GENERATED_FROM','EMBEDDED_LANGUAGE','CONSUMES','PRODUCES']);
function hash(v){return crypto.createHash('sha256').update(typeof v==='string'?v:parser.canon(v)).digest('hex');}
function identity(a){if(!a||typeof a!=='object'||Array.isArray(a))throw Error('SEMANTIC_ADAPTER_INVALID');const x={id:String(a.id||''),implementation:String(a.implementation||''),version:String(a.version||'UNKNOWN'),artifactSha256:String(a.artifactSha256||'UNBOUND'),deterministic:a.deterministic===true,offlineReady:a.offlineReady===true,languages:Array.isArray(a.languages)?[...new Set(a.languages.map(String))].sort():[]};if(!x.id||!x.implementation)throw Error('SEMANTIC_ADAPTER_IDENTITY_MISSING');if(!x.deterministic)throw Error('SEMANTIC_ADAPTER_NOT_DETERMINISTIC');if(!x.offlineReady)throw Error('SEMANTIC_ADAPTER_NOT_OFFLINE_READY');if(typeof a.index!=='function')throw Error('SEMANTIC_ADAPTER_INDEX_MISSING');return Object.freeze({...x,adapterSha256:hash(x)});}
function node(x,i,lid){if(!x||typeof x!=='object')throw Error(`SEMANTIC_NODE_INVALID:${i}`);const base={kind:String(x.kind||''),nativeKind:String(x.nativeKind||x.kind||''),languageId:String(x.languageId||lid),documentId:String(x.documentId||'document'),symbol:x.symbol==null?null:String(x.symbol),displayName:x.displayName==null?null:String(x.displayName),startByte:x.startByte==null?null:Number(x.startByte),endByte:x.endByte==null?null:Number(x.endByte),native:x.native&&typeof x.native==='object'&&!Array.isArray(x.native)?JSON.parse(JSON.stringify(x.native)):null};if(!base.kind)throw Error(`SEMANTIC_NODE_KIND_MISSING:${i}`);const nodeId=String(x.nodeId||`sgn.${hash({...base,i}).slice(0,28)}`);return Object.freeze({nodeId,...base,nodeSha256:hash({nodeId,...base})});}
function edge(x,i,ids){if(!x||typeof x!=='object')throw Error(`SEMANTIC_EDGE_INVALID:${i}`);const kind=String(x.kind||'');if(!EDGE_KINDS.includes(kind))throw Error(`SEMANTIC_EDGE_KIND_INVALID:${i}:${kind}`);const from=String(x.from||''),to=String(x.to||'');if(!ids.has(from)||!ids.has(to))throw Error(`SEMANTIC_EDGE_NODE_UNKNOWN:${i}`);const base={kind,from,to,nativeKind:x.nativeKind==null?null:String(x.nativeKind),attributes:x.attributes&&typeof x.attributes==='object'&&!Array.isArray(x.attributes)?JSON.parse(JSON.stringify(x.attributes)):null};const edgeId=String(x.edgeId||`sge.${hash({...base,i}).slice(0,28)}`);return Object.freeze({edgeId,...base,edgeSha256:hash({edgeId,...base})});}
function build({source,syntaxPassport,structuralReport=null,adapter,documentId='document'}={}){const bytes=parser.sourceBuffer(source);if(!syntaxPassport||syntaxPassport.schema!=='axm.code.syntax-passport.v1')throw Error('SEMANTIC_SYNTAX_PASSPORT_REQUIRED');if(parser.hashBytes(bytes)!==syntaxPassport.source?.sha256)throw Error('SEMANTIC_SOURCE_DIGEST_MISMATCH');const a=identity(adapter);if(a.languages.length&&!a.languages.includes(syntaxPassport.languageId))return Object.freeze({schema:'axm.code.semantic-graph.v1',result:'SEMANTIC_LANGUAGE_UNSUPPORTED',languageId:syntaxPassport.languageId,authority:'NONE'});const raw=adapter.index({languageId:syntaxPassport.languageId,documentId:String(documentId),source:Buffer.from(bytes),syntaxPassport,structuralReport});if(raw&&typeof raw.then==='function')throw Error('ASYNC_SEMANTIC_ADAPTER_NOT_ALLOWED');const rn=Array.isArray(raw?.nodes)?raw.nodes:[],re=Array.isArray(raw?.edges)?raw.edges:[];if(rn.length>500000||re.length>2000000)throw Error('SEMANTIC_GRAPH_LIMIT');const nodes=rn.map((x,i)=>node(x,i,syntaxPassport.languageId));if(new Set(nodes.map(x=>x.nodeId)).size!==nodes.length)throw Error('SEMANTIC_NODE_ID_DUPLICATE');const ids=new Set(nodes.map(x=>x.nodeId));const edges=re.map((x,i)=>edge(x,i,ids));if(new Set(edges.map(x=>x.edgeId)).size!==edges.length)throw Error('SEMANTIC_EDGE_ID_DUPLICATE');const core={schema:'axm.code.semantic-graph.v1',version:'1.0.0',result:'SEMANTIC_GRAPH_READY',languageId:syntaxPassport.languageId,organId:syntaxPassport.organId,documentId:String(documentId),sourceSha256:syntaxPassport.source.sha256,syntaxPassportSha256:syntaxPassport.syntaxPassportSha256,structuralReportSha256:structuralReport?.reportSha256||null,adapter:a,nodeCount:nodes.length,edgeCount:edges.length,nodes,edges,truth:{nativeFactsRetained:true,normalizedGraphIsNotRuntimeProof:true,aiRequired:false,networkRequired:false},authority:AUTHORITY};return Object.freeze({...core,graphSha256:hash(core)});}
module.exports={AUTHORITY,EDGE_KINDS,identity,build};
