'use strict';

const crypto=require('crypto');
const parser=require('./parser-spine.js');
const renderer=require('./candidate-renderer.js');

const AUTHORITY=Object.freeze({workspaceRead:false,workspaceMutation:false,toolExecution:false,network:false,install:false,promotion:false,canon:false});
const MAX_VERIFIERS=64;
function canon(v){return parser.canon(v);}
function hash(v){return crypto.createHash('sha256').update(typeof v==='string'?v:canon(v)).digest('hex');}
function verifierIdentity(v){if(!v||typeof v!=='object'||Array.isArray(v))throw Error('VERIFIER_INVALID');const body={id:String(v.id||''),kind:String(v.kind||'verifier'),implementation:String(v.implementation||''),version:String(v.version||'UNKNOWN'),artifactSha256:String(v.artifactSha256||'UNBOUND'),deterministic:v.deterministic===true,offlineReady:v.offlineReady===true,costRank:Number.isFinite(v.costRank)?Number(v.costRank):100};if(!body.id||!body.implementation)throw Error('VERIFIER_IDENTITY_MISSING');if(!body.deterministic)throw Error(`VERIFIER_NOT_DETERMINISTIC:${body.id}`);if(!body.offlineReady)throw Error(`VERIFIER_NOT_OFFLINE_READY:${body.id}`);if(typeof v.verify!=='function')throw Error(`VERIFIER_FUNCTION_MISSING:${body.id}`);return Object.freeze({...body,verifierSha256:hash(body)});}
function normalizeResult(x,id){if(!x||typeof x!=='object'||Array.isArray(x))throw Error(`VERIFIER_RESULT_INVALID:${id}`);const state=String(x.state||'UNKNOWN');if(!['PASS','FAIL','HOLD','UNKNOWN'].includes(state))throw Error(`VERIFIER_STATE_INVALID:${id}:${state}`);const facts=Array.isArray(x.facts)?x.facts.map(v=>String(v)):[];return Object.freeze({state,facts,summary:x.summary==null?null:String(x.summary),evidence:x.evidence&&typeof x.evidence==='object'&&!Array.isArray(x.evidence)?JSON.parse(JSON.stringify(x.evidence)):null});}
function verify({languageId,candidate,parserAdapter=null,verifiers=[]}={}){if(!candidate||candidate.schema!=='axm.code.candidate-render.v1'||candidate.result!=='CANDIDATE_BYTES_READY'||!Buffer.isBuffer(candidate.outputBytes))throw Error('VERIFIER_CANDIDATE_REQUIRED');if(!Array.isArray(verifiers)||verifiers.length>MAX_VERIFIERS)throw Error('VERIFIER_COUNT_INVALID');const steps=[];let state='PASS';if(parserAdapter){const syntax=parser.parse({languageId,source:candidate.outputBytes,adapter:parserAdapter});const parseState=syntax.result==='PARSED'?'PASS':'FAIL';steps.push({stage:'REPARSE',state:parseState,evidenceSha256:syntax.syntaxPassportSha256,errorCount:syntax.syntax?.errorCount??null});if(parseState!=='PASS')state='FAIL';}else{steps.push({stage:'REPARSE',state:'HOLD',reason:'NO_PARSER_ADAPTER'});state='HOLD';}
 const ranked=verifiers.map(v=>({raw:v,id:verifierIdentity(v)})).sort((a,b)=>a.id.costRank-b.id.costRank||a.id.id.localeCompare(b.id.id));if(state!=='FAIL')for(const item of ranked){const raw=item.raw.verify({languageId,source:Buffer.from(candidate.outputBytes),candidate});if(raw&&typeof raw.then==='function')throw Error(`ASYNC_VERIFIER_NOT_ALLOWED:${item.id.id}`);const result=normalizeResult(raw,item.id.id);steps.push({stage:'LOCAL_VERIFIER',verifier:item.id,result});if(result.state==='FAIL'){state='FAIL';break;}if(result.state==='HOLD'||result.state==='UNKNOWN'){state='HOLD';break;}}
 const core={schema:'axm.code.verification-ladder-report.v1',version:'1.0.0',result:state==='PASS'?'VERIFIED_CANDIDATE':state==='FAIL'?'CANDIDATE_REJECTED':'CANDIDATE_HELD',languageId,candidateSha256:candidate.candidateSha256,inputSha256:candidate.input.sha256,outputSha256:candidate.output.sha256,steps,truth:{cheapestFalsifierFirst:true,passIsBoundToExecutedLocalAdapters:true,missingVerifierIsNotPass:true,aiRequired:false,networkRequired:false,workspaceMutated:false},authority:AUTHORITY};return Object.freeze({...core,verificationSha256:hash(core)});}
module.exports={AUTHORITY,MAX_VERIFIERS,verifierIdentity,verify};
